baselines
projectParasol: spec
  spec
    for: #'squeakCommon'
    do: [ 
      spec
        configuration: 'Parasol'
        with: [ 
          spec
            repository: 'http://ss3.gemtalksystems.com/ss/Parasol';
            version: '0.23' ] ].
  spec
    for: #'gemstone'
    do: [ 
      spec
        configuration: 'Parasol'
        with: [ 
          spec
            repository: 'http://ss3.gemtalksystems.com/ss/Parasol';
            version: '0.23' ] ]