baselines
projectMagritte: spec
  spec
    for: #'squeakCommon'
    do: [ 
      spec
        configuration: 'Magritte3'
        with: [ 
          spec
            repository: 'http://www.smalltalkhub.com/mc/Magritte/Magritte3/main';
            version: '3.3.0' ] ].
  spec
    for: #'gemstone'
    do: [ 
      spec
        configuration: 'Magritte3'
        with: [ 
          spec
            repository: 'http://www.smalltalkhub.com/mc/Magritte/Magritte3/main';
            version: '3.3.0' ] ]